service: scoops-test
frameworkVersion: '3'

custom:
  userName: 'users-table-${sls:stage}'
  roleName: 'roles-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:CreateTable
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
            - Fn::GetAtt: [ RolesTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.userName}
    ROLES_TABLE: ${self:custom.roleName}

package:
  excludeDevDependencies: true
  exclude:
    - .dynamodb/**

functions:
  api:
    handler: index.handler
    environment:
      DATABASE_TYPE: dynamo
    events:
      - httpApi: '*'

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.userName}
    RolesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.roleName}

plugins:
  - serverless-offline
  - serverless-dynamodb-local
