@URL=https://35aljrgifl.execute-api.us-west-2.amazonaws.com/users

### GET users
GET {{URL}}

### POST users
POST {{URL}}
content-type: application/json

{
  "id": "user1",
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "password123",
  "roleId": "admin"
}


### get user by id
GET {{URL}}/1
