@URL=https://elclc20b2e.execute-api.us-west-2.amazonaws.com/users

### GET users
GET {{URL}}

### POST users
POST {{URL}}
content-type: application/json

{
    "userId": "2",
    "name": "newUser2@gmail.com"
}

### get user by id
GET {{URL}}/1
